# fly.toml app configuration file generated for cs-visualizer on 2026-08-31T22:54:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cs-visualizer'
primary_region = 'cdg'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "csviz_data"
  destination = "/app/data"

[build]
  dockerfile = "docker/Dockerfile"


[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
