<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CsViz.Ai\CsViz.Ai.csproj" />
    <ProjectReference Include="..\CsViz.Analysis\CsViz.Analysis.csproj" />
    <ProjectReference Include="..\CsViz.Core\CsViz.Core.csproj" />
    <ProjectReference Include="..\CsViz.Trace\CsViz.Trace.csproj" />
  </ItemGroup>

</Project>
